"""Shared backend configuration constants."""

SAMPLE_INTERVAL_SECONDS = 5.0
FRAME_STRIDE = 30
MIN_SAMPLE_INTERVAL_SECONDS = 0.1
MAX_SAMPLE_INTERVAL_SECONDS = 3600.0
DEFAULT_BATCH_SIZE = 64
MIN_BATCH_SIZE = 1
MAX_BATCH_SIZE = 256
PROGRESS_WRITE_INTERVAL_SECONDS = 1.0
MAX_COLLECTION_PROGRESS_UPDATES = 100
